// Generated by scripts/generate-tokens.ts from assets/colors. Do not edit by hand.
// Values are sRGB [red, green, blue, alpha]. Display P3 tokens converted to sRGB:
// Destructive, InfoSurface, StatusDeclined, StatusDeclinedText, StatusPending, StatusPendingText.

export type Rgba = readonly [number, number, number, number];

export interface ColorTokenValue {
  readonly light: Rgba;
  readonly dark?: Rgba;
  readonly highContrastLight?: Rgba;
  readonly highContrastDark?: Rgba;
}

export const colorTokens = {
  brandRocket: { light: [115, 134, 109, 1], dark: [118, 150, 118, 1] },
  brandSage: { light: [58, 103, 68, 1], dark: [114, 176, 123, 1] },
  brandSageSoft: { light: [210, 230, 210, 1], dark: [35, 57, 37, 1] },
  chart1: { light: [190, 199, 188, 1], dark: [172, 190, 158, 1] },
  chart2: { light: [107, 121, 105, 1], dark: [118, 150, 118, 1] },
  chart3: { light: [80, 92, 79, 1], dark: [106, 123, 93, 1] },
  chart4: { light: [55, 64, 54, 1], dark: [85, 99, 75, 1] },
  chart5: { light: [36, 43, 35, 1], dark: [66, 75, 59, 1] },
  destructive: { light: [231, 0, 11, 1], dark: [232, 96, 93, 1] },
  hairline: { light: [198, 205, 197, 1], dark: [90, 96, 85, 0.26], highContrastLight: [147, 155, 146, 1], highContrastDark: [124, 131, 120, 1] },
  hairlineSubtle: { light: [34, 41, 33, 0.07], dark: [226, 230, 224, 0.1], highContrastLight: [34, 41, 33, 0.3], highContrastDark: [226, 230, 224, 0.35] },
  infoBorder: { light: [186, 219, 254, 1], dark: [47, 103, 112, 1] },
  infoSurface: { light: [235, 246, 255, 1], dark: [27, 50, 54, 1] },
  ink: { light: [34, 41, 33, 1], dark: [226, 230, 224, 1] },
  inkFill: { light: [45, 54, 43, 1], dark: [223, 227, 220, 1] },
  inkSecondary: { light: [87, 97, 85, 1], dark: [145, 152, 141, 1], highContrastLight: [65, 75, 64, 1], highContrastDark: [180, 185, 176, 1] },
  inkTertiary: { light: [87, 97, 85, 0.6], dark: [145, 152, 141, 0.6], highContrastLight: [87, 97, 85, 1], highContrastDark: [160, 167, 156, 1] },
  onInkFill: { light: [238, 242, 238, 1], dark: [34, 37, 31, 1] },
  statusConfirmed: { light: [38, 117, 67, 1], dark: [114, 176, 123, 1] },
  statusConfirmedBright: { light: [90, 182, 107, 1], dark: [90, 182, 107, 1] },
  statusConfirmedText: { light: [38, 117, 67, 1], dark: [114, 176, 123, 1] },
  statusDeclined: { light: [172, 0, 44, 1], dark: [210, 75, 91, 1] },
  statusDeclinedBright: { light: [221, 76, 94, 1], dark: [221, 76, 94, 1] },
  statusDeclinedText: { light: [172, 0, 44, 1], dark: [237, 115, 124, 1] },
  statusInfo: { light: [52, 126, 196, 1], dark: [112, 191, 205, 1] },
  statusInfoText: { light: [48, 108, 165, 1], dark: [112, 191, 205, 1] },
  statusPending: { light: [195, 132, 0, 1], dark: [228, 182, 93, 1] },
  statusPendingBright: { light: [233, 171, 43, 1], dark: [233, 171, 43, 1] },
  statusPendingText: { light: [151, 98, 0, 1], dark: [228, 182, 93, 1] },
  surfaceCanvas: { light: [238, 242, 238, 1], dark: [30, 34, 28, 1] },
  surfaceCard: { light: [244, 247, 243, 1], dark: [40, 44, 36, 1] },
  surfaceHighlight: { light: [219, 226, 219, 1], dark: [50, 57, 48, 1] },
  surfaceInput: { light: [198, 205, 197, 0.5], dark: [90, 96, 85, 0.17] },
  surfaceMuted: { light: [224, 230, 224, 1], dark: [44, 49, 41, 1] },
  surfaceRaised: { light: [244, 247, 243, 1], dark: [42, 46, 39, 1] },
  surfaceSecondary: { light: [224, 230, 224, 1], dark: [49, 54, 46, 1] },
} as const satisfies Record<string, ColorTokenValue>;

export type ColorTokenName = keyof typeof colorTokens;

/** One value per token, such as a dynamic color for each. */
export const mapColorTokens = <Value>(
  make: (name: ColorTokenName) => Value
): Record<ColorTokenName, Value> => ({
  brandRocket: make("brandRocket"),
  brandSage: make("brandSage"),
  brandSageSoft: make("brandSageSoft"),
  chart1: make("chart1"),
  chart2: make("chart2"),
  chart3: make("chart3"),
  chart4: make("chart4"),
  chart5: make("chart5"),
  destructive: make("destructive"),
  hairline: make("hairline"),
  hairlineSubtle: make("hairlineSubtle"),
  infoBorder: make("infoBorder"),
  infoSurface: make("infoSurface"),
  ink: make("ink"),
  inkFill: make("inkFill"),
  inkSecondary: make("inkSecondary"),
  inkTertiary: make("inkTertiary"),
  onInkFill: make("onInkFill"),
  statusConfirmed: make("statusConfirmed"),
  statusConfirmedBright: make("statusConfirmedBright"),
  statusConfirmedText: make("statusConfirmedText"),
  statusDeclined: make("statusDeclined"),
  statusDeclinedBright: make("statusDeclinedBright"),
  statusDeclinedText: make("statusDeclinedText"),
  statusInfo: make("statusInfo"),
  statusInfoText: make("statusInfoText"),
  statusPending: make("statusPending"),
  statusPendingBright: make("statusPendingBright"),
  statusPendingText: make("statusPendingText"),
  surfaceCanvas: make("surfaceCanvas"),
  surfaceCard: make("surfaceCard"),
  surfaceHighlight: make("surfaceHighlight"),
  surfaceInput: make("surfaceInput"),
  surfaceMuted: make("surfaceMuted"),
  surfaceRaised: make("surfaceRaised"),
  surfaceSecondary: make("surfaceSecondary"),
});
