/**
 * Renders the contract model as Swift source for the `PCOBoosterCore` package: one file per
 * contract module, `Procedures.swift` with the `RPC` descriptors, and `Shared.swift` support.
 */
import path from "node:path";

import type {
  ContractModel,
  EnumCase,
  EnumModel,
  FieldModel,
  NamedType,
  ProcedureModel,
  StructModel,
  UnionModel,
} from "./model";
import { enumCases } from "./model";
import {
  camelCaseIdentifier,
  isSwiftIdentifier,
  pascalCase,
  propertyNameForKey,
  swiftIdentifier,
  swiftStringLiteral,
} from "./naming";

export interface GeneratedFile {
  /** Repository-relative path. */
  readonly path: string;
  readonly contents: string;
}

export const GENERATED_DIRECTORY =
  "apps/ios/PCOBoosterCore/Sources/PCOBoosterCore/API/Generated";

const CONTRACTS_PREFIX = "packages/contracts/";
const ROUTER_MODULE = "packages/contracts/src/router.ts";
const PROCEDURES_FILE = "Procedures.swift";
const SHARED_FILE = "Shared.swift";
const LINE_WIDTH = 100;
const INDENT = "  ";

const header = (source: string): string[] => [
  `// Generated by \`bun run ios:models\` from ${source}; do not edit.`,
  "// `scripts/ios/generate-swift-models.test.ts` fails when this file no longer matches the contracts.",
  "",
  "import Foundation",
];

const BACKTICK = "`";

/** Splits on spaces, keeping each `code span` whole so a wrap never breaks one. */
const docWords = (paragraph: string): string[] => {
  const tokens: string[] = [];
  let open = "";
  for (const word of paragraph.split(" ")) {
    const token = open === "" ? word : `${open} ${word}`;
    const ticks = token.split(BACKTICK).length - 1;
    if (ticks % 2 === 1) {
      open = token;
    } else {
      tokens.push(token);
      open = "";
    }
  }
  if (open !== "") {
    tokens.push(open);
  }
  return tokens;
};

/** Word-wraps a doc comment to `LINE_WIDTH`, keeping blank lines as paragraph breaks. */
const docComment = (text: string, indent: string): string[] => {
  const lines: string[] = [];
  const prefix = `${indent}/// `;
  for (const paragraph of text.split("\n")) {
    if (paragraph === "") {
      lines.push(`${indent}///`);
      continue;
    }
    let line = "";
    for (const word of docWords(paragraph)) {
      const candidate = line === "" ? word : `${line} ${word}`;
      if (line !== "" && prefix.length + candidate.length > LINE_WIDTH) {
        lines.push(`${prefix}${line}`);
        line = word;
      } else {
        line = candidate;
      }
    }
    lines.push(`${prefix}${line}`);
  }
  return lines;
};

export const swiftFileName = (module: string): string => {
  const base = path.basename(module, ".ts");
  if (module.startsWith(CONTRACTS_PREFIX)) {
    return `${pascalCase(base)}.swift`;
  }
  const packageName = path.basename(path.dirname(path.dirname(module)));
  return `${pascalCase(packageName)}${pascalCase(base)}.swift`;
};

const fieldType = (field: FieldModel, inputReachable: boolean): string => {
  switch (field.presence) {
    case "required":
    case "defaulted": {
      return field.type;
    }
    case "optional":
    case "nullable": {
      return `${field.type}?`;
    }
    case "nullish": {
      return inputReachable ? `Nullable<${field.type}>?` : `${field.type}?`;
    }
    default: {
      throw new Error(`Unknown presence for ${field.key}`);
    }
  }
};

const initDefault = (field: FieldModel): string => {
  if (field.presence === "required" || field.presence === "defaulted") {
    return field.initDefault === undefined ? "" : ` = ${field.initDefault}`;
  }
  return " = nil";
};

const decodeLine = (field: FieldModel, inputReachable: boolean): string => {
  const target = `self.${swiftIdentifier(field.name)}`;
  const key = `.${swiftIdentifier(field.name)}`;
  const type = `${field.type}.self`;
  switch (field.presence) {
    case "required": {
      return `${target} = try container.decode(${type}, forKey: ${key})`;
    }
    case "defaulted": {
      return `${target} = try container.decodeIfPresent(${type}, forKey: ${key}) ?? ${field.initDefault ?? "nil"}`;
    }
    case "nullish": {
      return inputReachable
        ? `${target} = try container.decodeNullable(${type}, forKey: ${key})`
        : `${target} = try container.decodeIfPresent(${type}, forKey: ${key})`;
    }
    case "optional":
    case "nullable": {
      return `${target} = try container.decodeIfPresent(${type}, forKey: ${key})`;
    }
    default: {
      throw new Error(`Unknown presence for ${field.key}`);
    }
  }
};

const encodeLine = (field: FieldModel): string => {
  const value = `self.${swiftIdentifier(field.name)}`;
  const key = `.${swiftIdentifier(field.name)}`;
  return field.presence === "optional" || field.presence === "nullish"
    ? `try container.encodeIfPresent(${value}, forKey: ${key})`
    : `try container.encode(${value}, forKey: ${key})`;
};

const codingKeysLines = (fields: readonly FieldModel[]): string[] => [
  `${INDENT}private enum CodingKeys: String, CodingKey {`,
  ...fields.map((field) =>
    field.renamed
      ? `${INDENT}${INDENT}case ${swiftIdentifier(field.name)} = ${swiftStringLiteral(field.key)}`
      : `${INDENT}${INDENT}case ${swiftIdentifier(field.name)}`
  ),
  `${INDENT}}`,
];

const initLines = (
  fields: readonly FieldModel[],
  inputReachable: boolean
): string[] => {
  if (fields.length === 0) {
    return [`${INDENT}public init() {}`];
  }
  const parameters = fields.map(
    (field) =>
      `${swiftIdentifier(field.name)}: ${fieldType(field, inputReachable)}${initDefault(field)}`
  );
  const assignments = fields.map(
    (field) =>
      `${INDENT}${INDENT}self.${swiftIdentifier(field.name)} = ${swiftIdentifier(field.name)}`
  );
  const oneLine = `${INDENT}public init(${parameters.join(", ")}) {`;
  if (oneLine.length <= LINE_WIDTH) {
    return [oneLine, ...assignments, `${INDENT}}`];
  }
  return [
    `${INDENT}public init(`,
    ...parameters.map(
      (parameter, index) =>
        `${INDENT}${INDENT}${parameter}${index === parameters.length - 1 ? "" : ","}`
    ),
    `${INDENT}) {`,
    ...assignments,
    `${INDENT}}`,
  ];
};

const renderStruct = (type: NamedType, model: StructModel): string[] => {
  const inputReachable = type.modes.has("input");
  const { fields } = model;
  const identifiable = fields.some(
    (field) =>
      field.name === "id" &&
      field.type === "String" &&
      (field.presence === "required" || field.presence === "defaulted")
  );
  const usesNullable =
    inputReachable && fields.some((field) => field.presence === "nullish");
  const customDecode =
    usesNullable || fields.some((field) => field.presence === "defaulted");
  const customEncode = fields.some((field) => field.presence === "nullable");
  const explicitKeys =
    customDecode || customEncode || fields.some((field) => field.renamed);
  const conformances = ["Codable", "Hashable", "Sendable"];
  if (identifiable) {
    conformances.push("Identifiable");
  }
  const lines = [
    ...docComment(type.doc, ""),
    `public struct ${type.name}: ${conformances.join(", ")} {`,
    ...fields.flatMap((field) => [
      ...(field.doc === undefined ? [] : docComment(field.doc, INDENT)),
      `${INDENT}public var ${swiftIdentifier(field.name)}: ${fieldType(field, inputReachable)}`,
    ]),
  ];
  if (fields.length > 0) {
    lines.push("");
  }
  lines.push(...initLines(fields, inputReachable));
  if (explicitKeys) {
    lines.push("", ...codingKeysLines(fields));
  }
  if (customDecode) {
    lines.push(
      "",
      `${INDENT}public init(from decoder: any Decoder) throws {`,
      `${INDENT}${INDENT}let container = try decoder.container(keyedBy: CodingKeys.self)`,
      ...fields.map(
        (field) => `${INDENT}${INDENT}${decodeLine(field, inputReachable)}`
      ),
      `${INDENT}}`
    );
  }
  if (customEncode) {
    lines.push(
      "",
      `${INDENT}public func encode(to encoder: any Encoder) throws {`,
      `${INDENT}${INDENT}var container = encoder.container(keyedBy: CodingKeys.self)`,
      ...fields.map((field) => `${INDENT}${INDENT}${encodeLine(field)}`),
      `${INDENT}}`
    );
  }
  lines.push("}");
  return lines;
};

interface TolerantEnum {
  readonly name: string;
  readonly doc: string;
  readonly cases: readonly EnumCase[];
  readonly caseDocs?: ReadonlyMap<string, string>;
}

const caseRef = (name: string): string => `.${swiftIdentifier(name)}`;

const renderTolerantEnum = (item: TolerantEnum): string[] => {
  const lines = [
    ...docComment(
      `${item.doc}\n\nValues this build does not know decode as \`unknown\` and encode back unchanged.`,
      ""
    ),
    `public enum ${item.name}: RawRepresentable, Codable, Hashable, Sendable, CaseIterable,`,
    `${INDENT}CodingKeyRepresentable`,
    "{",
  ];
  for (const { name, value } of item.cases) {
    const caseDoc = item.caseDocs?.get(value);
    if (caseDoc !== undefined) {
      lines.push(...docComment(caseDoc, INDENT));
    }
    lines.push(`${INDENT}case ${swiftIdentifier(name)}`);
  }
  const allCases = `${INDENT}public static let allCases: [${item.name}] = [${item.cases.map(({ name }) => caseRef(name)).join(", ")}]`;
  lines.push(
    `${INDENT}case unknown(String)`,
    "",
    `${INDENT}/// The values the contract defines; never \`unknown\`.`,
    ...(allCases.length <= LINE_WIDTH
      ? [allCases]
      : [
          `${INDENT}public static let allCases: [${item.name}] = [`,
          ...item.cases.map(
            ({ name }) => `${INDENT}${INDENT}${caseRef(name)},`
          ),
          `${INDENT}]`,
        ]),
    "",
    `${INDENT}public init(rawValue: String) {`,
    `${INDENT}${INDENT}switch rawValue {`,
    ...item.cases.map(
      ({ name, value }) =>
        `${INDENT}${INDENT}case ${swiftStringLiteral(value)}: self = ${caseRef(name)}`
    ),
    `${INDENT}${INDENT}default: self = .unknown(rawValue)`,
    `${INDENT}${INDENT}}`,
    `${INDENT}}`,
    "",
    `${INDENT}public var rawValue: String {`,
    `${INDENT}${INDENT}switch self {`,
    ...item.cases.map(
      ({ name, value }) =>
        `${INDENT}${INDENT}case ${caseRef(name)}: ${swiftStringLiteral(value)}`
    ),
    `${INDENT}${INDENT}case .unknown(let value): value`,
    `${INDENT}${INDENT}}`,
    `${INDENT}}`,
    "",
    `${INDENT}public init(from decoder: any Decoder) throws {`,
    `${INDENT}${INDENT}self.init(rawValue: try decoder.singleValueContainer().decode(String.self))`,
    `${INDENT}}`,
    "",
    `${INDENT}public func encode(to encoder: any Encoder) throws {`,
    `${INDENT}${INDENT}var container = encoder.singleValueContainer()`,
    `${INDENT}${INDENT}try container.encode(rawValue)`,
    `${INDENT}}`,
    "",
    `${INDENT}public var codingKey: any CodingKey {`,
    `${INDENT}${INDENT}ContractCodingKey(rawValue)`,
    `${INDENT}}`,
    "",
    `${INDENT}public init?<Key: CodingKey>(codingKey: Key) {`,
    `${INDENT}${INDENT}self.init(rawValue: codingKey.stringValue)`,
    `${INDENT}}`,
    "}"
  );
  return lines;
};

const renderEnum = (type: NamedType, model: EnumModel): string[] =>
  renderTolerantEnum({ cases: model.cases, doc: type.doc, name: type.name });

const renderUnion = (type: NamedType, model: UnionModel): string[] => {
  const key = propertyNameForKey(model.discriminator);
  const keyCase = swiftIdentifier(key.name);
  const keyDeclaration = key.renamed
    ? `case ${keyCase} = ${swiftStringLiteral(model.discriminator)}`
    : `case ${keyCase}`;
  const lines = [
    ...docComment(type.doc, ""),
    `public enum ${type.name}: Codable, Hashable, Sendable {`,
    ...model.variants.map(({ name, payload }) =>
      payload === undefined
        ? `${INDENT}case ${swiftIdentifier(name)}`
        : `${INDENT}case ${swiftIdentifier(name)}(${payload})`
    ),
    `${INDENT}/// A \`${model.discriminator}\` this build does not know.`,
    `${INDENT}case unknown(String)`,
    "",
    `${INDENT}private enum DiscriminatorKey: String, CodingKey {`,
    `${INDENT}${INDENT}${keyDeclaration}`,
    `${INDENT}}`,
    "",
    `${INDENT}public init(from decoder: any Decoder) throws {`,
    `${INDENT}${INDENT}let container = try decoder.container(keyedBy: DiscriminatorKey.self)`,
    `${INDENT}${INDENT}let value = try container.decode(String.self, forKey: .${keyCase})`,
    `${INDENT}${INDENT}switch value {`,
    ...model.variants.map(({ name, payload, value }) =>
      payload === undefined
        ? `${INDENT}${INDENT}case ${swiftStringLiteral(value)}: self = .${swiftIdentifier(name)}`
        : `${INDENT}${INDENT}case ${swiftStringLiteral(value)}: self = try .${swiftIdentifier(name)}(${payload}(from: decoder))`
    ),
    `${INDENT}${INDENT}default: self = .unknown(value)`,
    `${INDENT}${INDENT}}`,
    `${INDENT}}`,
    "",
    `${INDENT}public func encode(to encoder: any Encoder) throws {`,
    `${INDENT}${INDENT}var container = encoder.container(keyedBy: DiscriminatorKey.self)`,
    `${INDENT}${INDENT}switch self {`,
  ];
  for (const { name, payload, value } of model.variants) {
    if (payload === undefined) {
      lines.push(
        `${INDENT}${INDENT}case .${swiftIdentifier(name)}:`,
        `${INDENT}${INDENT}${INDENT}try container.encode(${swiftStringLiteral(value)}, forKey: .${keyCase})`
      );
    } else {
      lines.push(
        `${INDENT}${INDENT}case .${swiftIdentifier(name)}(let payload):`,
        `${INDENT}${INDENT}${INDENT}try container.encode(${swiftStringLiteral(value)}, forKey: .${keyCase})`,
        `${INDENT}${INDENT}${INDENT}try payload.encode(to: encoder)`
      );
    }
  }
  lines.push(
    `${INDENT}${INDENT}case .unknown(let value):`,
    `${INDENT}${INDENT}${INDENT}try container.encode(value, forKey: .${keyCase})`,
    `${INDENT}${INDENT}}`,
    `${INDENT}}`,
    "}"
  );
  return lines;
};

const renderType = (type: NamedType): string[] => {
  const { model } = type;
  if (model === undefined) {
    throw new Error(`${type.name} was named but never modeled`);
  }
  switch (model.kind) {
    case "struct": {
      return renderStruct(type, model);
    }
    case "enum": {
      return renderEnum(type, model);
    }
    case "union": {
      return renderUnion(type, model);
    }
    case "alias": {
      return [
        ...docComment(type.doc, ""),
        `public typealias ${type.name} = ${model.target}`,
      ];
    }
    default: {
      throw new Error(`Unknown model for ${type.name}`);
    }
  }
};

const joinBlocks = (blocks: readonly (readonly string[])[]): string =>
  `${blocks.map((block) => block.join("\n")).join("\n\n")}\n`;

const byName = (left: NamedType, right: NamedType): number => {
  if (left.name === right.name) {
    return 0;
  }
  return left.name < right.name ? -1 : 1;
};

interface Namespace {
  readonly procedures: ProcedureModel[];
  readonly children: Map<string, Namespace>;
}

const procedureTree = (procedures: readonly ProcedureModel[]): Namespace => {
  const root: Namespace = { children: new Map(), procedures: [] };
  for (const procedure of procedures) {
    let node = root;
    for (const key of procedure.keys.slice(0, -1)) {
      const child = node.children.get(key) ?? {
        children: new Map(),
        procedures: [],
      };
      node.children.set(key, child);
      node = child;
    }
    node.procedures.push(procedure);
  }
  return root;
};

const memberName = (key: string): string =>
  swiftIdentifier(isSwiftIdentifier(key) ? key : camelCaseIdentifier(key));

const sentence = (text: string): string =>
  text.endsWith(".") ? text : `${text}.`;

const procedureDoc = (procedure: ProcedureModel): string => {
  const label = procedure.keys.join(".");
  const route =
    procedure.httpPath === undefined
      ? ""
      : `, REST \`${procedure.method ?? "POST"} ${procedure.httpPath}\``;
  const errors =
    procedure.errorCodes.length === 0
      ? "Errors: none declared."
      : `Errors: ${procedure.errorCodes.map((code) => `\`${code}\``).join(", ")}.`;
  const input = procedure.hasInput
    ? ""
    : " Declares no input, so the request body is `{}`.";
  const output =
    procedure.outputDoc === undefined
      ? ""
      : `\n\nOutput: ${procedure.outputDoc}`;
  return `${sentence(procedure.summary ?? label)}${output}\n\nContract \`${label}\` in \`${procedure.module}\`${route}.${input} ${errors}`;
};

const procedureLines = (
  procedure: ProcedureModel,
  indent: string
): string[] => {
  const name = memberName(procedure.keys.at(-1) ?? "");
  const pathLiteral = swiftStringLiteral(procedure.keys.join("/"));
  const call = `Procedure<${procedure.inputType}, ${procedure.outputType}>(${pathLiteral}${procedure.hasInput ? "" : ", hasInput: false"})`;
  const oneLine = `${indent}public static let ${name} = ${call}`;
  return [
    ...docComment(procedureDoc(procedure), indent),
    ...(oneLine.length <= LINE_WIDTH
      ? [oneLine]
      : [`${indent}public static let ${name} =`, `${indent}${INDENT}${call}`]),
  ];
};

const namespaceLines = (node: Namespace, indent: string): string[][] => {
  const blocks: string[][] = node.procedures.map((procedure) =>
    procedureLines(procedure, indent)
  );
  for (const [key, child] of node.children) {
    blocks.push([
      `${indent}public enum ${pascalCase(key)} {`,
      namespaceLines(child, `${indent}${INDENT}`)
        .map((block) => block.join("\n"))
        .join("\n\n"),
      `${indent}}`,
    ]);
  }
  return blocks;
};

const namespaceNames = (node: Namespace): string[] =>
  [...node.children].flatMap(([key, child]) => [
    pascalCase(key),
    ...namespaceNames(child),
  ]);

const errorCodeDoc = (dataTypes: readonly string[]): string | undefined => {
  if (dataTypes.length === 0) {
    return undefined;
  }
  const names = dataTypes.map((name) => `\`${name}\``);
  return dataTypes.length === 1
    ? `When \`defined\`, its \`data\` decodes as ${names[0]}.`
    : `When \`defined\`, its \`data\` decodes as ${names.join(" or ")}, depending on the procedure.`;
};

const renderProcedures = (model: ContractModel): string => {
  const tree = procedureTree(model.procedures);
  const typeNames = new Set(model.types.map(({ name }) => name));
  for (const namespace of namespaceNames(tree)) {
    if (typeNames.has(namespace)) {
      throw new Error(
        `The RPC.${namespace} namespace would hide the generated type ${namespace}; rename one`
      );
    }
  }
  const paths = model.procedures.map(
    ({ keys }) => `${INDENT}${INDENT}${swiftStringLiteral(keys.join("/"))},`
  );
  const rpc = [
    ...docComment(
      `Every procedure in \`appContract\` (\`${ROUTER_MODULE}\`). Each is called as \`POST /api/rpc/<path>\` with the body \`{"json": input}\`, or \`{}\` when \`hasInput\` is false.`,
      ""
    ),
    "public enum RPC {",
    namespaceLines(tree, INDENT)
      .map((block) => block.join("\n"))
      .join("\n\n"),
    "",
    `${INDENT}/// Every procedure path, in router order.`,
    `${INDENT}public static let allPaths: [String] = [`,
    ...paths,
    `${INDENT}]`,
    "}",
  ];
  const caseDocs = new Map(
    model.errorCodes.flatMap(({ code, dataTypes }) => {
      const doc = errorCodeDoc(dataTypes);
      return doc === undefined ? [] : [[code, doc] as const];
    })
  );
  const errorCodes = renderTolerantEnum({
    caseDocs,
    cases: enumCases(model.errorCodes.map(({ code }) => code)),
    doc: "Every error `code` the contract procedures declare. Undeclared codes, such as `METHOD_NOT_SUPPORTED` or `CLIENT_CLOSED_REQUEST`, decode as `unknown`.",
    name: "ContractErrorCode",
  });
  return joinBlocks([header(`\`${ROUTER_MODULE}\``), rpc, errorCodes]);
};

/** Every generated Swift file, keyed by repository-relative path, in path order. */
export const renderSwiftFiles = (
  model: ContractModel,
  sharedSwift: string
): GeneratedFile[] => {
  const byFile = new Map<string, { module: string; types: NamedType[] }>();
  for (const type of model.types) {
    const fileName = swiftFileName(type.file);
    if (fileName === PROCEDURES_FILE || fileName === SHARED_FILE) {
      throw new Error(
        `${type.file} would overwrite ${fileName}; rename the module`
      );
    }
    const group = byFile.get(fileName) ?? { module: type.file, types: [] };
    group.types.push(type);
    byFile.set(fileName, group);
  }
  const files: GeneratedFile[] = [...byFile].map(([fileName, group]) => ({
    contents: joinBlocks([
      header(`\`${group.module}\``),
      ...group.types.toSorted(byName).map((type) => renderType(type)),
    ]),
    path: `${GENERATED_DIRECTORY}/${fileName}`,
  }));
  files.push(
    {
      contents: renderProcedures(model),
      path: `${GENERATED_DIRECTORY}/${PROCEDURES_FILE}`,
    },
    {
      contents: joinBlocks([
        header("`scripts/ios/swift-models/Shared.template.swift`"),
        [sharedSwift],
      ]),
      path: `${GENERATED_DIRECTORY}/${SHARED_FILE}`,
    }
  );
  return files.toSorted((left, right) => (left.path < right.path ? -1 : 1));
};
