/**
 * Synthetic media for the audio and video fixtures, so fixture launches play in the system
 * player with no network: a tone generated here, and a test pattern generated by
 * `scripts/generate-fixture-video.sh`. Neither is a recording of anything.
 */
import fixtureVideo from "./fixture-video.json";

const SAMPLE_RATE = 8000;
const TONE_HZ = 440;
const TONE_SECONDS = 2;
/** 8-bit PCM is unsigned: silence is 128. */
const SILENCE = 128;
const AMPLITUDE = 90;
const WAV_HEADER_BYTES = 44;
const FADE_SAMPLES = 400;

/** A 2-second 440 Hz tone as an 8 kHz, 8-bit mono WAV file, in base64. */
export const fixtureToneWav = (): string => {
  const samples = SAMPLE_RATE * TONE_SECONDS;
  const bytes = new Uint8Array(WAV_HEADER_BYTES + samples);
  const view = new DataView(bytes.buffer);
  const ascii = (offset: number, text: string) => {
    for (let index = 0; index < text.length; index += 1) {
      view.setUint8(offset + index, text.codePointAt(index) ?? 0);
    }
  };
  ascii(0, "RIFF");
  view.setUint32(4, WAV_HEADER_BYTES - 8 + samples, true);
  ascii(8, "WAVE");
  ascii(12, "fmt ");
  view.setUint32(16, 16, true);
  // PCM, one channel, the sample rate, bytes per second, block align, bits per sample.
  view.setUint16(20, 1, true);
  view.setUint16(22, 1, true);
  view.setUint32(24, SAMPLE_RATE, true);
  view.setUint32(28, SAMPLE_RATE, true);
  view.setUint16(32, 1, true);
  view.setUint16(34, 8, true);
  ascii(36, "data");
  view.setUint32(40, samples, true);
  for (let index = 0; index < samples; index += 1) {
    const fade = Math.min(
      1,
      index / FADE_SAMPLES,
      (samples - index) / FADE_SAMPLES
    );
    const wave = Math.sin((2 * Math.PI * TONE_HZ * index) / SAMPLE_RATE);
    bytes[WAV_HEADER_BYTES + index] = Math.round(
      SILENCE + AMPLITUDE * fade * wave
    );
  }
  let binary = "";
  for (const byte of bytes) {
    binary += String.fromCodePoint(byte);
  }
  return btoa(binary);
};

export interface FixtureMedia {
  /** The file name the player opens; its extension tells AVFoundation the format. */
  readonly name: string;
  readonly base64: () => string;
}

/** Each fixture attachment with playable media, by id (`songs.attachmentLink.json`). */
export const fixtureMedia = new Map<string, FixtureMedia>([
  ["88001", { name: "Morning Light - Demo.wav", base64: fixtureToneWav }],
  [
    "88002",
    { name: "Morning Light - Rehearsal.mp4", base64: () => fixtureVideo.mp4 },
  ],
]);
